# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ci-document-classification-demo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ikonnecttschoolcontentintelligenceacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3942947236c54f708d46329424c43d9d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_89d73d37a15a4e2b8c48bbe2704d0297 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ikonnecttschoolcontentintelligenceacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3942947236c54f708d46329424c43d9d }}/ci-document-classification:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ci-document-classification-demo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9f94eac1619f4b9782f8ec5689d6a59c }}
        images: 'ikonnecttschoolcontentintelligenceacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3942947236c54f708d46329424c43d9d }}/ci-document-classification:${{ github.sha }}'